version: "3"

tasks:
  install:
    desc: "install local dependencies"
    cmds:
      - poetry install --sync --no-root --all-extras

  lint:
    desc: "run linters"
    cmds:
      - poetry run ruff format .
      - poetry run ruff check . --fix
      - poetry run mypy .

  lint-ci:
    desc: "run linters"
    cmds:
      - poetry run ruff format . --check
      - poetry run ruff check . --no-fix
      - poetry run mypy .

  tests:
    desc: "run pytest (pass args after '--')"
    cmds:
      - poetry run pytest {{.CLI_ARGS}}

  release:
    desc: "bump version, create tag and release, publish to PYPI"
    cmds:
      - git checkout main
      - git pull
      - rm -rf ./dist
      - poetry version {{.CLI_ARGS}}
      - git add pyproject.toml
      - git commit -m "bump version to {{.CLI_ARGS}}"
      - poetry build
      - twine upload dist/*
      - git tag {{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}
      - gh release upload {{.CLI_ARGS}} ./dist/*
